# Generated by Django 5.2.17 on 2026-10-05 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='reservation_amount_paise_nonnegative',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='amount_paise',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gte', 0), ('amount_paise__lte', 2147483647)), name='reservation_amount_paise_range'),
        ),
    ]
